apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1T
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data
    server: 10.39.55.66
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  # Specify "" as the storageClassName so it matches the PersistentVolume's StorageClass.
  # A nil storageClassName value uses the default StorageClass. For details, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: nfs
  resources:
    requests:
      storage: 1T
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
          readOnly: false
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/nvoss-php-nfs-demo/cloud-run-source-deploy/filesystem-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /var/www/html
          name: nfs
